name: Flutter manual build

on:
  workflow_dispatch:
    inputs:
      upload_artifact:
        description: "Upload build artifacts"
        required: true
        default: "true"
      upload_tag:
        description: "Tag name used by the build"
        required: true
        default: "nightly"

jobs:
  build:
    uses: ./.github/workflows/flutter-build.yml
    with:
      upload-artifact: ${{ github.event.inputs.upload_artifact == 'true' }}
      upload-tag: ${{ github.event.inputs.upload_tag }}
